name: GitHub Actions Demo
on: [push]
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: install pytest
        run: pip install pytest
        
      - name: run script python
        run: python moyenne.py
